# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get install wkhtmltopdf -y
          sudo apt-get install python-tk -y
          sudo apt-get install python3 pip -y

      # Runs a set of commands using the runners shell
      - name: Install pip Dependencies
        run: |
          pip install markdown
          pip install pdfkit
          pip install pandas
          pip install wkhtmltopdf
          pip install tk
          pip install tabulate

      # Runs a set of commands using the runners shell
      - name: Convert CSV to MD
        run: |
          python3 Registry/Py/CSVtoMD.py

      # Runs a set of commands using the runners shell
      - name: Convert CSV to Json
        run: |
          python3 Registry/Py/CSVtoJSON.py

      # Runs a set of commands using the runners shell
      - name: Convert MD to PDF
        run: |
          python3 Research/Py/MDtoPDF.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
